server:
  port: 8084

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: DRIVER-SERVICE
          uri: lb://DRIVER-SERVICE
          predicates:
            - Path=/driver-service/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka


